name: check
on: push
jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: cd client
        run: cd client
      - name: install client
        run: npm ci
        working-directory: ./client
      - name: test client
        run: npm run test
      - name: cd server
        run: cd ../server
      - name: install server
        run: npm ci
      - name: test server
        run: npm run test
