name: check
on: push
jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: install client
        run: npm ci
        working-directory: ./client
      - name: test client
        run: npm run test
        working-directory: ./client
      - name: install server
        run: npm ci
        working-directory: ./server
      - name: test server
        run: npm run test
        working-directory: ./client
